### PR TITLE
Update rubocop dependency to 0.36.0

### PR DESCRIPTION
**Pull request by juno**
Release notes: https://github.com/bbatsov/rubocop/releases/tag/v0.36.0

### CODE REVIEW

**Comment by sanemat** [comment]
Old bundler brings these failing tests.
This issue fixed in v1.10 or later.

Use `sudo: false` and/or `gem update bundler` in `.travis.yml`. :helicopter: 

See: [NoMethodError: undefined method `spec' for nil:NilClass · Issue #3558 · bundler/bundler](https://github.com/bundler/bundler/issues/3558)

**Comment by juno** [comment]
@sanemat Good catch! I fixed it.

**Comment by mmozuras** [comment]
@juno thanks!

Released as `v0.5.1`.

**Comment by juno** [comment]
@mmozuras Thank you!

Unfortunately we need to fix one more issue to work with rubocop 0.36.0.
I just created PR #19 and it was tested on my local environment, please review. :bow:
